import { Roboto } from 'next/font/google';
import './globals.css';
import Header from "src/components/layout/Header";
import {SessionProvider} from "next-auth/react";
import {AppProvider} from "@/components/AppContext";

const roboto = Roboto({ subsets: ['latin'] , weight: ['400', '500', '700']})

export const metadata = {
  title: 'Gloverse',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
      <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
              <Header />
              {children}
              <footer className="border-t p-8 text-center text-grey-500 mt-16">
                  &copy; 2023 All rights reserved
              </footer>
          </AppProvider>
      </main>
      </body>
    </html>
  )
}
